services:
  - type: web
    name: physiology-pro
    runtime: static
    repo: https://github.com/sumaiyamohammadwajeeh2019/Physiology-pro-GP-calculators
    branch: main
    buildCommand: echo "static site - no build needed"
    staticPublishPath: ./
